apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  namespace: monitoring
  name: nut-exporter
  labels:
spec:
  selector:
    matchLabels:
      app: prometheus-nut-exporter
  podMetricsEndpoints:
  - port: metrics
    params: { target: ["olymp.lan.mnl.de:3493"] }
    # See https://github.com/prometheus-operator/prometheus-operator/issues/135
    relabelings:
    - action: replace
      targetLabel: instance
      sourceLabels:
      - __meta_kubernetes_pod_node_name
