apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  namespace: monitoring
  name: prometheus
  labels:
    app: prometheus
spec:
  serviceAccountName: prometheus
  # All ServiceMonitors in own namespace
  serviceMonitorSelector: {}
  # All PodMonitors in own namespace
  podMonitorSelector: {}
  # Additional
  additionalScrapeConfigs:
    name: additional-scrape-configs
    key: prometheus-additional.yaml
  resources:
    requests:
      memory: 400Mi
  # Remove the rest if you don't need long term storage
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: rook-cephfs
        resources:
          requests:
            storage: 40Gi
  securityContext:
    fsGroup: 65534
