apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  namespace: monitoring
  name: node-exporters
  labels:
spec:
  selector:
    matchLabels:
      app: node-exporter
  podMetricsEndpoints:
  - port: metrics
    # See https://github.com/prometheus-operator/prometheus-operator/issues/135
    relabelings:
    - action: replace
      targetLabel: instance
      sourceLabels:
      - __meta_kubernetes_pod_node_name
