apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/release-0.70/bundle.yaml
- 20_service-account.yaml
- 30_cluster-role.yaml
- 40_cluster-role-binding.yaml
- 45_additional
- 50_prometheus.yaml
- 60_prometheus-service.yaml
- 70_pod-monitor_node-exporter.yaml
- 80_service-monitor-rook-ceph-mgr.yaml
- 90_service-kubelet-metrics.yaml

patches:
- patch: |-
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: prometheuses.monitoring.coreos.com
      annotations:
        argocd.argoproj.io/sync-options: ServerSideApply=true
