apiVersion: v1
kind: ConfigMap
metadata:
  namespace: rook-ceph
  name: grafana-config
data:
  grafana.ini: |
    [auth.anonymous]
    enabled = true
    org_name = Main Org.
    org_role = Viewer

    [security]
    disable_initial_admin_creation = true
    allow_embedding = true

    [users]
    default_theme = light

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: rook-ceph
  name: grafana-datasources
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
    - name: Dashboard1
      orgId: 1
      type: prometheus
      url: http://prometheus.monitoring:9090
      isDefault: true
      version: 1
      editable: false
      
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: rook-ceph
  name: grafana-dashboards
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
    - name: ceph-dashboard
      orgId: 1
      folder: 'ceph-dashboard'
      type: file
      disableDeletion: true
      updateIntervalSeconds: 60
      allowUiUpdates: false
      options:
        path: /var/run/grafana-dashboards
