apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
- name: additional-scrape-configs
  namespace: monitoring
  files:
  - prometheus-additional.yaml

generatorOptions:
  disableNameSuffixHash: true
