{
 "title": "Ceph - Cluster",
 "description": "Ceph cluster overview",
 "tags": [
  "ceph",
  "cluster"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Health Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "ceph_health_status" }
   ]
  },
  {
   "title": "OSDs",
   "type": "vonage-status-panel",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "All",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "count(ceph_osd_metadata)",
     "legendFormat": "All",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "In",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(ceph_osd_in)",
     "legendFormat": "In",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "Out",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(ceph_osd_in == bool 0)",
     "legendFormat": "Out",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 1
    },
    {
     "aggregation": "Last",
     "alias": "Up",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(ceph_osd_up)",
     "legendFormat": "Up",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "Down",
     "crit": 2,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(ceph_osd_up == bool 0)",
     "legendFormat": "Down",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 1
    }
   ]
  },
  {
   "title": "Capacity used",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ceph_osd_stat_bytes_used)/sum(ceph_osd_stat_bytes)",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "PG States",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(ceph_pg_total)", "legendFormat": "Total" },
    { "expr": "sum(ceph_pg_active)", "legendFormat": "Active" },
    {
     "expr": "sum(ceph_pg_total - ceph_pg_active)",
     "legendFormat": "Inactive"
    },
    { "expr": "sum(ceph_pg_undersized)", "legendFormat": "Undersized" },
    { "expr": "sum(ceph_pg_degraded)", "legendFormat": "Degraded" },
    { "expr": "sum(ceph_pg_inconsistent)", "legendFormat": "Inconsistent" },
    { "expr": "sum(ceph_pg_down)", "legendFormat": "Down" }
   ]
  },
  {
   "title": "OSD Latencies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "quantile(0.95, ceph_osd_apply_latency_ms)",
     "legendFormat": "Apply Latency P_95"
    },
    {
     "expr": "quantile(0.95, ceph_osd_commit_latency_ms)",
     "legendFormat": "Commit Latency P_95"
    },
    { "expr": "avg(ceph_osd_apply_latency_ms)", "legendFormat": "Avg Apply Latency" },
    {
     "expr": "avg(ceph_osd_commit_latency_ms)",
     "legendFormat": "Avg Commit Latency"
    }
   ]
  },
  {
   "title": "Monitors",
   "type": "vonage-status-panel",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "In Quorum",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(ceph_mon_quorum_status)",
     "legendFormat": "In Quorum",
     "units": "none",
     "valueHandler": "Text Only"
    },
    {
     "aggregation": "Last",
     "alias": "Total",
     "crit": 1,
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "count(ceph_mon_quorum_status)",
     "legendFormat": "Total",
     "units": "none",
     "valueHandler": "Text Only",
     "warn": 2
    },
    {
     "aggregation": "Last",
     "alias": "MONs out of Quorum",
     "crit": 1.6,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Annotation",
     "displayValueWithAlias": "Never",
     "expr": "count(ceph_mon_quorum_status) / sum(ceph_mon_quorum_status)",
     "legendFormat": "MONs out of Quorum",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 1.1
    }
   ]
  },
  {
   "title": "MGRs",
   "type": "vonage-status-panel",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "Active",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "count(ceph_mgr_status == 1) or vector(0)",
     "legendFormat": "Active",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "Standby",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "count(ceph_mgr_status == 0) or vector(0)",
     "legendFormat": "Standby",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Cluster I/O",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "Bps", "label": "Read (-) / Write (+)" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_op_w_in_bytes[1m]))",
     "legendFormat": "Writes"
    },
    {
     "expr": "sum(irate(ceph_osd_op_r_out_bytes[1m]))",
     "legendFormat": "Reads"
    }
   ]
  },
  {
   "title": "In-/Egress",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "Bps", "label": " Egress (-) / Ingress (+)" }
   ],
   "targets": [
    {
     "expr": "sum(deriv(ceph_pool_stored[1m]))"
    }
   ]
  },
  {
   "title": "OSD Capacity Utilization",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "ceph_osd_stat_bytes_used / ceph_osd_stat_bytes",
     "legendFormat": "Util (%)"
    }
   ]
  },
  {
   "title": "PGs per OSD",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 15 },
   "targets": [
    { "expr": "ceph_osd_numpg", "legendFormat": "#PGs" }
   ]
  },
  {
   "title": "Recovery Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "ops", "label": "Recovery Ops/s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_recovery_ops[1m]))",
     "legendFormat": "Op/s"
    }
   ]
  }
 ]
}
{
 "title": "MDS Performance",
 "tags": [ "ceph-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(ceph_osd_metadata, cluster)"
   },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(ceph_osd_metadata{}, job)"
   },
   {
    "name": "mds_servers",
    "label": "MDS Server",
    "query": "label_values(ceph_mds_inodes{job=~\"$job\"}, ceph_daemon)"
   }
  ]
 },
 "panels": [
  { "title": "MDS Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MDS Workload - $mds_servers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none", "label": "Reads(-) / Writes (+)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ceph_objecter_op_r{job=~\"$job\", ceph_daemon=~\"($mds_servers).*\"}[$__rate_interval]))",
     "legendFormat": "Read Ops"
    },
    {
     "expr": "sum(rate(ceph_objecter_op_w{job=~\"$job\", ceph_daemon=~\"($mds_servers).*\"}[$__rate_interval]))",
     "legendFormat": "Write Ops"
    }
   ]
  },
  {
   "title": "Client Request Load - $mds_servers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "none", "label": "Client Requests" }
   ],
   "targets": [
    {
     "expr": "ceph_mds_server_handle_client_request{job=~\"$job\", ceph_daemon=~\"($mds_servers).*\"}",
     "legendFormat": "{{ceph_daemon}}"
    }
   ]
  }
 ]
}
{
 "title": "Host Details",
 "tags": [
  "ceph-mixin",
  "overview"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(ceph_osd_metadata, cluster)"
   },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(ceph_osd_metadata{}, job)"
   },
   { "name": "ceph_hosts", "label": "Hostname", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  { "title": "$ceph_hosts System Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "OSDs",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(sum by (ceph_daemon) (ceph_osd_metadata{job=~\"$job\", hostname='$ceph_hosts'}))"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "description": "Shows the CPU breakdown. When multiple servers are selected, only the first host's cpu data is shown",
   "gridPos": { "h": 10, "w": 6, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "percent", "label": "% Utilization" }
   ],
   "targets": [
    {
     "expr": "sum by (mode) (\n  rate(node_cpu{instance=~\"($ceph_hosts)([\\\\\\\\.:].*)?\", mode=~\"(irq|nice|softirq|steal|system|user|iowait)\"}[$__rate_interval]) or\n  rate(node_cpu_seconds_total{instance=~\"($ceph_hosts)([\\\\\\\\.:].*)?\", mode=~\"(irq|nice|softirq|steal|system|user|iowait)\"}[$__rate_interval])\n) / (\n  scalar(\n    sum(rate(node_cpu{instance=~\"($ceph_hosts)([\\\\\\\\.:].*)?\"}[$__rate_interval]) or\n    rate(node_cpu_seconds_total{instance=~\"($ceph_hosts)([\\\\\\\\.:].*)?\"}[$__rate_interval]))\n  ) * 100\n)\n",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "bytes", "label": "RAM used" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree{instance=~\"$ceph_hosts([\\\\\\\\.:].*)?\"} or\n  node_memory_MemFree_bytes{instance=~\"$ceph_hosts([\\\\\\\\.:].*)?\"}\n",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_MemTotal{instance=~\"$ceph_hosts([\\\\\\\\.:].*)?\"} or\n  node_memory_MemTotal_bytes{instance=~\"$ceph_hosts([\\\\\\\\.:].*)?\"}\n",
     "legendFormat": "total"
    },
    {
     "expr": "(\n  node_memory_Cached{instance=~\"$ceph_hosts([\\\\\\\\.:].*)?\"} or\n  node_memory_Cached_bytes{instance=~\"$ceph_hosts([\\\\\\\\.:].*)?\"}\n) + (\n  node_memory_Buffers{instance=~\"$ceph_hosts([\\\\\\\\.:].*)?\"} or\n  node_memory_Buffers_bytes{instance=~\"$ceph_hosts([\\\\\\\\.:].*)?\"}\n) + (\n  node_memory_Slab{instance=~\"$ceph_hosts([\\\\\\\\.:].*)?\"} or\n  node_memory_Slab_bytes{instance=~\"$ceph_hosts([\\\\\\\\.:].*)?\"}\n)\n",
     "legendFormat": "buffers/cache"
    },
    {
     "expr": "(\n  node_memory_MemTotal{instance=~\"$ceph_hosts([\\\\\\\\.:].*)?\"} or\n  node_memory_MemTotal_bytes{instance=~\"$ceph_hosts([\\\\\\\\.:].*)?\"}\n) - (\n  (\n    node_memory_MemFree{instance=~\"$ceph_hosts([\\\\\\\\.:].*)?\"} or\n    node_memory_MemFree_bytes{instance=~\"$ceph_hosts([\\\\\\\\.:].*)?\"}\n  ) + (\n    node_memory_Cached{instance=~\"$ceph_hosts([\\\\\\\\.:].*)?\"} or\n    node_memory_Cached_bytes{instance=~\"$ceph_hosts([\\\\\\\\.:].*)?\"}\n  ) + (\n    node_memory_Buffers{instance=~\"$ceph_hosts([\\\\\\\\.:].*)?\"} or\n    node_memory_Buffers_bytes{instance=~\"$ceph_hosts([\\\\\\\\.:].*)?\"}\n  ) +\n  (\n    node_memory_Slab{instance=~\"$ceph_hosts([\\\\\\\\.:].*)?\"} or\n    node_memory_Slab_bytes{instance=~\"$ceph_hosts([\\\\\\\\.:].*)?\"}\n  )\n)\n",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Network Load",
   "type": "graph",
   "description": "Show the network load (rx,tx) across all interfaces (excluding loopback 'lo')",
   "gridPos": { "h": 10, "w": 6, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "decbytes", "label": "Send (-) / Receive (+)" }
   ],
   "targets": [
    {
     "expr": "sum by (device) (\n  rate(\n    node_network_receive_bytes{instance=~\"($ceph_hosts)([\\\\\\\\.:].*)?\",device!=\"lo\"}[$__rate_interval]) or\n    rate(node_network_receive_bytes_total{instance=~\"($ceph_hosts)([\\\\\\\\.:].*)?\",device!=\"lo\"}[$__rate_interval]\n  )\n)\n",
     "legendFormat": "{{device}}.rx"
    },
    {
     "expr": "sum by (device) (\n  rate(node_network_transmit_bytes{instance=~\"($ceph_hosts)([\\\\\\\\.:].*)?\",device!=\"lo\"}[$__rate_interval]) or\n  rate(node_network_transmit_bytes_total{instance=~\"($ceph_hosts)([\\\\\\\\.:].*)?\",device!=\"lo\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{device}}.tx"
    }
   ]
  },
  {
   "title": "Network drop rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "yaxes": [
    { "format": "pps", "label": "Send (-) / Receive (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_drop{instance=~\"$ceph_hosts([\\\\\\\\.:].*)?\"}[$__rate_interval]) or\n  rate(node_network_receive_drop_total{instance=~\"$ceph_hosts([\\\\\\\\.:].*)?\"}[$__rate_interval])\n",
     "legendFormat": "{{device}}.rx"
    },
    {
     "expr": "rate(node_network_transmit_drop{instance=~\"$ceph_hosts([\\\\\\\\.:].*)?\"}[$__rate_interval]) or\n  rate(node_network_transmit_drop_total{instance=~\"$ceph_hosts([\\\\\\\\.:].*)?\"}[$__rate_interval])\n",
     "legendFormat": "{{device}}.tx"
    }
   ]
  },
  {
   "title": "Raw Capacity",
   "type": "singlestat",
   "description": "Each OSD consists of a Journal/WAL partition and a data partition. The RAW Capacity shown is the sum of the data partitions across all OSDs on the selected OSD hosts.",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n  ceph_osd_stat_bytes{job=~\"$job\"} and\n    on (ceph_daemon) ceph_disk_occupation{job=~\"$job\", instance=~\"($ceph_hosts)([\\\\\\\\.:].*)?\"}\n)\n"
    }
   ]
  },
  {
   "title": "Network error rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 6 },
   "yaxes": [
    { "format": "pps", "label": "Send (-) / Receive (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_errs{instance=~\"$ceph_hosts([\\\\\\\\.:].*)?\"}[$__rate_interval]) or\n  rate(node_network_receive_errs_total{instance=~\"$ceph_hosts([\\\\\\\\.:].*)?\"}[$__rate_interval])\n",
     "legendFormat": "{{device}}.rx"
    },
    {
     "expr": "rate(node_network_transmit_errs{instance=~\"$ceph_hosts([\\\\\\\\.:].*)?\"}[$__rate_interval]) or\n  rate(node_network_transmit_errs_total{instance=~\"$ceph_hosts([\\\\\\\\.:].*)?\"}[$__rate_interval])\n",
     "legendFormat": "{{device}}.tx"
    }
   ]
  },
  {
   "title": "OSD Disk Performance Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }
  },
  {
   "title": "$ceph_hosts Disk IOPS",
   "type": "graph",
   "description": "For any OSD devices on the host, this chart shows the iops per physical device. Each device is shown by it's name and corresponding OSD id value",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ops", "label": "Read (-) / Write (+)" }
   ],
   "targets": [
    {
     "expr": "label_replace(\n  (\n    rate(node_disk_writes_completed{instance=~\"($ceph_hosts)([\\\\\\\\.:].*)?\"}[$__rate_interval]) or\n    rate(node_disk_writes_completed_total{instance=~\"($ceph_hosts)([\\\\\\\\.:].*)?\"}[$__rate_interval])\n  ), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n) * on(instance, device) group_left(ceph_daemon) label_replace(\n  label_replace(\n    ceph_disk_occupation_human{job=~\"$job\"}, \"device\", \"$1\", \"device\", \"/dev/(.*)\"\n  ), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n)\n",
     "legendFormat": "{{device}}({{ceph_daemon}}) writes"
    },
    {
     "expr": "label_replace(\n  (\n    rate(node_disk_reads_completed{instance=~\"($ceph_hosts)([\\\\\\\\.:].*)?\"}[$__rate_interval]) or\n    rate(node_disk_reads_completed_total{instance=~\"($ceph_hosts)([\\\\\\\\.:].*)?\"}[$__rate_interval])\n  ), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n) * on(instance, device) group_left(ceph_daemon) label_replace(\n  label_replace(\n    ceph_disk_occupation_human{job=~\"$job\"},\"device\", \"$1\", \"device\", \"/dev/(.*)\"\n  ), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n)\n",
     "legendFormat": "{{device}}({{ceph_daemon}}) reads"
    }
   ]
  },
  {
   "title": "$ceph_hosts Throughput by Disk",
   "type": "graph",
   "description": "For OSD hosts, this chart shows the disk bandwidth (read bytes/sec + write bytes/sec) of the physical OSD device. Each device is shown by device name, and corresponding OSD id",
   "gridPos": { "h": 9, "w": 11, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "Bps", "label": "Read (-) / Write (+)" }
   ],
   "targets": [
    {
     "expr": "label_replace(\n  (\n    rate(node_disk_bytes_written{instance=~\"($ceph_hosts)([\\\\\\\\.:].*)?\"}[$__rate_interval]) or\n    rate(node_disk_written_bytes_total{instance=~\"($ceph_hosts)([\\\\\\\\.:].*)?\"}[$__rate_interval])\n  ), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\") * on(instance, device)\n  group_left(ceph_daemon) label_replace(\n    label_replace(ceph_disk_occupation_human{job=~\"$job\"}, \"device\", \"$1\", \"device\", \"/dev/(.*)\"),\n    \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n  )\n",
     "legendFormat": "{{device}}({{ceph_daemon}}) write"
    },
    {
     "expr": "label_replace(\n  (\n    rate(node_disk_bytes_read{instance=~\"($ceph_hosts)([\\\\\\\\.:].*)?\"}[$__rate_interval]) or\n    rate(node_disk_read_bytes_total{instance=~\"($ceph_hosts)([\\\\\\\\.:].*)?\"}[$__rate_interval])\n  ),\n  \"instance\", \"$1\", \"instance\", \"([^:.]*).*\") * on(instance, device)\n  group_left(ceph_daemon) label_replace(\n    label_replace(ceph_disk_occupation_human{job=~\"$job\"}, \"device\", \"$1\", \"device\", \"/dev/(.*)\"),\n    \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n  )\n",
     "legendFormat": "{{device}}({{ceph_daemon}}) read"
    }
   ]
  },
  {
   "title": "$ceph_hosts Disk Latency",
   "type": "graph",
   "description": "For OSD hosts, this chart shows the latency at the physical drive. Each drive is shown by device name, with it's corresponding OSD id",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max by(instance, device) (label_replace(\n  (rate(node_disk_write_time_seconds_total{instance=~\"($ceph_hosts)([\\\\\\\\.:].*)?\"}[$__rate_interval])) /\n    clamp_min(rate(node_disk_writes_completed_total{instance=~\"($ceph_hosts)([\\\\\\\\.:].*)?\"}[$__rate_interval]), 0.001) or\n    (rate(node_disk_read_time_seconds_total{instance=~\"($ceph_hosts)([\\\\\\\\.:].*)?\"}[$__rate_interval])) /\n      clamp_min(rate(node_disk_reads_completed_total{instance=~\"($ceph_hosts)([\\\\\\\\.:].*)?\"}[$__rate_interval]), 0.001),\n  \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n)) * on(instance, device) group_left(ceph_daemon) label_replace(\n  label_replace(\n    ceph_disk_occupation_human{instance=~\"($ceph_hosts)([\\\\\\\\.:].*)?\"},\n    \"device\", \"$1\", \"device\", \"/dev/(.*)\"\n  ), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n)\n",
     "legendFormat": "{{device}}({{ceph_daemon}})"
    }
   ]
  },
  {
   "title": "$ceph_hosts Disk utilization",
   "type": "graph",
   "description": "Show disk utilization % (util) of any OSD devices on the host by the physical device name and associated OSD id.",
   "gridPos": { "h": 9, "w": 11, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "percent", "label": "%Util" }
   ],
   "targets": [
    {
     "expr": "label_replace(\n  (\n    (rate(node_disk_io_time_ms{instance=~\"($ceph_hosts)([\\\\\\\\.:].*)?\"}[$__rate_interval]) / 10) or\n    rate(node_disk_io_time_seconds_total{instance=~\"($ceph_hosts)([\\\\\\\\.:].*)?\"}[$__rate_interval]) * 100\n  ), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n) * on(instance, device) group_left(ceph_daemon) label_replace(\n  label_replace(ceph_disk_occupation_human{job=~\"$job\", instance=~\"($ceph_hosts)([\\\\\\\\.:].*)?\"},\n  \"device\", \"$1\", \"device\", \"/dev/(.*)\"), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n)\n",
     "legendFormat": "{{device}}({{ceph_daemon}})"
    }
   ]
  },
  {
   "title": "Top Slow Ops per Host",
   "type": "table",
   "description": "This table shows the 10 hosts with the highest number of slow ops",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "topk(10,\n  (sum by (instance)(ceph_daemon_health_metrics{type=\"SLOW_OPS\", ceph_daemon=~\"osd.*\"}))\n)\n"
    }
   ]
  }
 ]
}
{
 "title": "Host Overview",
 "tags": [ "ceph-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(ceph_osd_metadata, cluster)"
   },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(ceph_osd_metadata{}, job)"
   },
   {
    "name": "osd_hosts",
    "query": "label_values(ceph_disk_occupation{job=~\"$job\"}, exported_instance)"
   },
   {
    "name": "mon_hosts",
    "query": "label_values(ceph_mon_metadata{job=~\"$job\"}, ceph_daemon)"
   },
   {
    "name": "mds_hosts",
    "query": "label_values(ceph_mds_inodes{job=~\"$job\"}, ceph_daemon)"
   },
   {
    "name": "rgw_hosts",
    "query": "label_values(ceph_rgw_metadata{job=~\"$job\"}, ceph_daemon)"
   }
  ]
 },
 "panels": [
  {
   "title": "OSD Hosts",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(sum by (hostname) (ceph_osd_metadata{job=~\"$job\"}))"
    }
   ]
  },
  {
   "title": "AVG CPU Busy",
   "type": "singlestat",
   "description": "Average CPU busy across all hosts (OSD, RGW, MON etc) within the cluster",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(1 - (\n  avg by(instance) (\n    rate(node_cpu_seconds_total{mode='idle',instance=~\"($osd_hosts|$mon_hosts|$mds_hosts|$rgw_hosts).*\"}[$__rate_interval]) or\n    rate(node_cpu{mode='idle',instance=~\"($osd_hosts|$mon_hosts|$mds_hosts|$rgw_hosts).*\"}[$__rate_interval])\n  )\n))\n"
    }
   ]
  },
  {
   "title": "AVG RAM Utilization",
   "type": "singlestat",
   "description": "Average Memory Usage across all hosts in the cluster (excludes buffer/cache usage)",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg ((\n  (\n    node_memory_MemTotal{instance=~\"($osd_hosts|$mon_hosts|$mds_hosts|$rgw_hosts).*\"} or\n    node_memory_MemTotal_bytes{instance=~\"($osd_hosts|$mon_hosts|$mds_hosts|$rgw_hosts).*\"}\n  ) - ((\n    node_memory_MemFree{instance=~\"($osd_hosts|$mon_hosts|$mds_hosts|$rgw_hosts).*\"} or\n    node_memory_MemFree_bytes{instance=~\"($osd_hosts|$mon_hosts|$mds_hosts|$rgw_hosts).*\"}) +\n    (\n      node_memory_Cached{instance=~\"($osd_hosts|$mon_hosts|$mds_hosts|$rgw_hosts).*\"} or\n      node_memory_Cached_bytes{instance=~\"($osd_hosts|$mon_hosts|$mds_hosts|$rgw_hosts).*\"}\n    ) + (\n      node_memory_Buffers{instance=~\"($osd_hosts|$mon_hosts|$mds_hosts|$rgw_hosts).*\"} or\n      node_memory_Buffers_bytes{instance=~\"($osd_hosts|$mon_hosts|$mds_hosts|$rgw_hosts).*\"}\n    ) + (\n      node_memory_Slab{instance=~\"($osd_hosts|$mon_hosts|$mds_hosts|$rgw_hosts).*\"} or\n      node_memory_Slab_bytes{instance=~\"($osd_hosts|$mon_hosts|$mds_hosts|$rgw_hosts).*\"}\n    )\n  )\n) / (\n  node_memory_MemTotal{instance=~\"($osd_hosts|$mon_hosts|$mds_hosts|$rgw_hosts).*\"} or\n   node_memory_MemTotal_bytes{instance=~\"($osd_hosts|$rgw_hosts|$mon_hosts|$mds_hosts).*\"}\n))\n"
    }
   ]
  },
  {
   "title": "Physical IOPS",
   "type": "singlestat",
   "description": "IOPS Load at the device as reported by the OS on all OSD hosts",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum ((\n  rate(node_disk_reads_completed{instance=~\"($osd_hosts).*\"}[$__rate_interval]) or\n  rate(node_disk_reads_completed_total{instance=~\"($osd_hosts).*\"}[$__rate_interval])\n) + (\n  rate(node_disk_writes_completed{instance=~\"($osd_hosts).*\"}[$__rate_interval]) or\n  rate(node_disk_writes_completed_total{instance=~\"($osd_hosts).*\"}[$__rate_interval])\n))\n"
    }
   ]
  },
  {
   "title": "AVG Disk Utilization",
   "type": "singlestat",
   "description": "Average Disk utilization for all OSD data devices (i.e. excludes journal/WAL)",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg (\n  label_replace(\n    (rate(node_disk_io_time_ms[$__rate_interval]) / 10 ) or\n      (rate(node_disk_io_time_seconds_total[$__rate_interval]) * 100),\n    \"instance\", \"$1\", \"instance\", \"([^.:]*).*\"\n  ) * on(instance, device) group_left(ceph_daemon) label_replace(\n    label_replace(\n      ceph_disk_occupation_human{job=~\"$job\", instance=~\"($osd_hosts).*\"},\n      \"device\", \"$1\", \"device\", \"/dev/(.*)\"\n    ), \"instance\", \"$1\", \"instance\", \"([^.:]*).*\"\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Network Load",
   "type": "singlestat",
   "description": "Total send/receive network load across all hosts in the ceph cluster",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (\n  (\n    rate(node_network_receive_bytes{instance=~\"($osd_hosts|mon_hosts|mds_hosts|rgw_hosts).*\",device!=\"lo\"}[$__rate_interval]) or\n    rate(node_network_receive_bytes_total{instance=~\"($osd_hosts|mon_hosts|mds_hosts|rgw_hosts).*\",device!=\"lo\"}[$__rate_interval])\n  ) unless on (device, instance)\n  label_replace((bonding_slaves > 0), \"device\", \"$1\", \"master\", \"(.+)\")\n) +\nsum (\n  (\n    rate(node_network_transmit_bytes{instance=~\"($osd_hosts|mon_hosts|mds_hosts|rgw_hosts).*\",device!=\"lo\"}[$__rate_interval]) or\n    rate(node_network_transmit_bytes_total{instance=~\"($osd_hosts|mon_hosts|mds_hosts|rgw_hosts).*\",device!=\"lo\"}[$__rate_interval])\n  ) unless on (device, instance)\n  label_replace((bonding_slaves > 0), \"device\", \"$1\", \"master\", \"(.+)\")\n)\n"
    }
   ]
  },
  {
   "title": "CPU Busy - Top 10 Hosts",
   "type": "graph",
   "description": "Show the top 10 busiest hosts by cpu",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(10,\n  100 * (\n    1 - (\n      avg by(instance) (\n        rate(node_cpu_seconds_total{mode='idle',instance=~\"($osd_hosts|$mon_hosts|$mds_hosts|$rgw_hosts).*\"}[$__rate_interval]) or\n          rate(node_cpu{mode='idle',instance=~\"($osd_hosts|$mon_hosts|$mds_hosts|$rgw_hosts).*\"}[$__rate_interval])\n      )\n    )\n  )\n)\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Load - Top 10 Hosts",
   "type": "graph",
   "description": "Top 10 hosts by network load",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(10, (sum by(instance) (\n(\n  rate(node_network_receive_bytes{instance=~\"($osd_hosts|$mon_hosts|$mds_hosts|$rgw_hosts).*\",device!=\"lo\"}[$__rate_interval]) or\n  rate(node_network_receive_bytes_total{instance=~\"($osd_hosts|$mon_hosts|$mds_hosts|$rgw_hosts).*\",device!=\"lo\"}[$__rate_interval])\n) +\n(\n  rate(node_network_transmit_bytes{instance=~\"($osd_hosts|$mon_hosts|$mds_hosts|$rgw_hosts).*\",device!=\"lo\"}[$__rate_interval]) or\n  rate(node_network_transmit_bytes_total{instance=~\"($osd_hosts|$mon_hosts|$mds_hosts|$rgw_hosts).*\",device!=\"lo\"}[$__rate_interval])\n) unless on (device, instance)\n  label_replace((bonding_slaves > 0), \"device\", \"$1\", \"master\", \"(.+)\"))\n))\n",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}
{
 "title": "OSD device details",
 "tags": [ "ceph-mixin" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(ceph_osd_metadata, cluster)"
   },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(ceph_osd_metadata{}, job)"
   },
   {
    "name": "osd",
    "label": "OSD",
    "query": "label_values(ceph_osd_metadata{job=~\"$job\"}, ceph_daemon)"
   }
  ]
 },
 "panels": [
  { "title": "OSD Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$osd Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s", "label": "Read (-) / Write (+)" }
   ],
   "targets": [
    {
     "expr": "rate(ceph_osd_op_r_latency_sum{job=~\"$job\", ceph_daemon=~\"$osd\"}[$__rate_interval]) /\n  on (ceph_daemon) rate(ceph_osd_op_r_latency_count{job=~\"$job\"}[$__rate_interval])\n",
     "legendFormat": "read"
    },
    {
     "expr": "rate(ceph_osd_op_w_latency_sum{job=~\"$job\", ceph_daemon=~\"$osd\"}[$__rate_interval]) /\n  on (ceph_daemon) rate(ceph_osd_op_w_latency_count{job=~\"$job\"}[$__rate_interval])\n",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "$osd R/W IOPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Read (-) / Write (+)" }
   ],
   "targets": [
    {
     "expr": "rate(ceph_osd_op_r{job=~\"$job\", ceph_daemon=~\"$osd\"}[$__rate_interval])",
     "legendFormat": "Reads"
    },
    {
     "expr": "rate(ceph_osd_op_w{job=~\"$job\", ceph_daemon=~\"$osd\"}[$__rate_interval])",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "$osd R/W Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes", "label": "Read (-) / Write (+)" }
   ],
   "targets": [
    {
     "expr": "rate(ceph_osd_op_r_out_bytes{job=~\"$job\", ceph_daemon=~\"$osd\"}[$__rate_interval])",
     "legendFormat": "Read Bytes"
    },
    {
     "expr": "rate(ceph_osd_op_w_in_bytes{job=~\"$job\", ceph_daemon=~\"$osd\"}[$__rate_interval])",
     "legendFormat": "Write Bytes"
    }
   ]
  },
  { "title": "Physical Device Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Physical Device Latency for $osd",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "s", "label": "Read (-) / Write (+)" }
   ],
   "targets": [
    {
     "expr": "(\n  label_replace(\n    rate(node_disk_read_time_seconds_total{}[$__rate_interval]) /\n      rate(node_disk_reads_completed_total{}[$__rate_interval]),\n    \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n  ) and on (instance, device) label_replace(\n    label_replace(\n      ceph_disk_occupation_human{job=~\"$job\", ceph_daemon=~\"$osd\"},\n      \"device\", \"$1\", \"device\", \"/dev/(.*)\"\n    ), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n  )\n)\n",
     "legendFormat": "{{instance}}/{{device}} Reads"
    },
    {
     "expr": "(\n  label_replace(\n    rate(node_disk_write_time_seconds_total{}[$__rate_interval]) /\n      rate(node_disk_writes_completed_total{}[$__rate_interval]),\n    \"instance\", \"$1\", \"instance\", \"([^:.]*).*\") and on (instance, device)\n    label_replace(\n      label_replace(\n        ceph_disk_occupation_human{job=~\"$job\", ceph_daemon=~\"$osd\"}, \"device\", \"$1\", \"device\", \"/dev/(.*)\"\n      ), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n    )\n  )\n",
     "legendFormat": "{{instance}}/{{device}} Writes"
    }
   ]
  },
  {
   "title": "Physical Device R/W IOPS for $osd",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Read (-) / Write (+)" }
   ],
   "targets": [
    {
     "expr": "label_replace(\n  rate(node_disk_writes_completed_total{}[$__rate_interval]),\n  \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n) and on (instance, device) label_replace(\n  label_replace(\n    ceph_disk_occupation_human{job=~\"$job\", ceph_daemon=~\"$osd\"},\n    \"device\", \"$1\", \"device\", \"/dev/(.*)\"\n  ), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n)\n",
     "legendFormat": "{{device}} on {{instance}} Writes"
    },
    {
     "expr": "label_replace(\n  rate(node_disk_reads_completed_total{}[$__rate_interval]),\n  \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n) and on (instance, device) label_replace(\n  label_replace(\n    ceph_disk_occupation_human{job=~\"$job\", ceph_daemon=~\"$osd\"},\n    \"device\", \"$1\", \"device\", \"/dev/(.*)\"\n  ), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n)\n",
     "legendFormat": "{{device}} on {{instance}} Reads"
    }
   ]
  },
  {
   "title": "Physical Device R/W Bytes for $osd",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "Bps", "label": "Read (-) / Write (+)" }
   ],
   "targets": [
    {
     "expr": "label_replace(\n  rate(node_disk_read_bytes_total{}[$__rate_interval]), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n) and on (instance, device) label_replace(\n  label_replace(\n    ceph_disk_occupation_human{job=~\"$job\", ceph_daemon=~\"$osd\"},\n    \"device\", \"$1\", \"device\", \"/dev/(.*)\"\n  ), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n)\n",
     "legendFormat": "{{instance}} {{device}} Reads"
    },
    {
     "expr": "label_replace(\n  rate(node_disk_written_bytes_total{}[$__rate_interval]), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n) and on (instance, device) label_replace(\n  label_replace(\n    ceph_disk_occupation_human{job=~\"$job\", ceph_daemon=~\"$osd\"},\n    \"device\", \"$1\", \"device\", \"/dev/(.*)\"\n  ), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n)\n",
     "legendFormat": "{{instance}} {{device}} Writes"
    }
   ]
  },
  {
   "title": "Physical Device Util% for $osd",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "label_replace(\n  rate(node_disk_io_time_seconds_total{}[$__rate_interval]),\n  \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n) and on (instance, device) label_replace(\n  label_replace(\n    ceph_disk_occupation_human{job=~\"$job\", ceph_daemon=~\"$osd\"}, \"device\", \"$1\", \"device\", \"/dev/(.*)\"\n  ), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"\n)\n",
     "legendFormat": "{{device}} on {{instance}}"
    }
   ]
  }
 ]
}
{
 "title": "OSD Overview",
 "tags": [ "ceph-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(ceph_osd_metadata, cluster)"
   },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(ceph_osd_metadata{}, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "OSD Read Latencies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg (\n  rate(ceph_osd_op_r_latency_sum{job=~\"$job\"}[$__rate_interval]) /\n    on (ceph_daemon) rate(ceph_osd_op_r_latency_count{job=~\"$job\"}[$__rate_interval]) * 1000\n)\n",
     "legendFormat": "AVG read"
    },
    {
     "expr": "max(\n  rate(ceph_osd_op_r_latency_sum{job=~\"$job\"}[$__rate_interval]) /\n  on (ceph_daemon) rate(ceph_osd_op_r_latency_count{job=~\"$job\"}[$__rate_interval]) * 1000\n)\n",
     "legendFormat": "MAX read"
    },
    {
     "expr": "quantile(0.95,\n  (\n    rate(ceph_osd_op_r_latency_sum{job=~\"$job\"}[$__rate_interval]) /\n      on (ceph_daemon) rate(ceph_osd_op_r_latency_count{job=~\"$job\"}[$__rate_interval])\n      * 1000\n  )\n)\n",
     "legendFormat": "@95%ile"
    }
   ]
  },
  {
   "title": "Highest READ Latencies",
   "type": "table",
   "description": "This table shows the osd's that are delivering the 10 highest read latencies within the cluster",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "topk(10,\n  (sort(\n    (\n      rate(ceph_osd_op_r_latency_sum{job=~\"$job\"}[$__rate_interval]) /\n        on (ceph_daemon) rate(ceph_osd_op_r_latency_count{job=~\"$job\"}[$__rate_interval]) *\n        1000\n    )\n  ))\n)\n"
    }
   ]
  },
  {
   "title": "OSD Write Latencies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(\n  rate(ceph_osd_op_w_latency_sum{job=~\"$job\"}[$__rate_interval]) /\n    on (ceph_daemon) rate(ceph_osd_op_w_latency_count{job=~\"$job\"}[$__rate_interval])\n    * 1000\n)\n",
     "legendFormat": "AVG write"
    },
    {
     "expr": "max(\n  rate(ceph_osd_op_w_latency_sum{job=~\"$job\"}[$__rate_interval]) /\n    on (ceph_daemon) rate(ceph_osd_op_w_latency_count{job=~\"$job\"}[$__rate_interval]) *\n    1000\n)\n",
     "legendFormat": "MAX write"
    },
    {
     "expr": "quantile(0.95, (\n  rate(ceph_osd_op_w_latency_sum{job=~\"$job\"}[$__rate_interval]) /\n    on (ceph_daemon) rate(ceph_osd_op_w_latency_count{job=~\"$job\"}[$__rate_interval]) *\n    1000\n))\n",
     "legendFormat": "@95%ile write"
    }
   ]
  },
  {
   "title": "Highest WRITE Latencies",
   "type": "table",
   "description": "This table shows the osd's that are delivering the 10 highest write latencies within the cluster",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "expr": "topk(10,\n  (sort(\n    (rate(ceph_osd_op_w_latency_sum{job=~\"$job\"}[$__rate_interval]) /\n      on (ceph_daemon) rate(ceph_osd_op_w_latency_count{job=~\"$job\"}[$__rate_interval]) *\n      1000)\n  ))\n)\n"
    }
   ]
  },
  {
   "title": "OSD Types Summary",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "valueName": "current",
   "targets": [
    {
     "expr": "count by (device_class) (ceph_osd_metadata{job=~\"$job\"})",
     "legendFormat": "{{device_class}}"
    }
   ]
  },
  {
   "title": "OSD Objectstore Types",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 8 },
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ceph_bluefs_wal_total_bytes{job=~\"$job\"})",
     "legendFormat": "bluestore"
    },
    {
     "expr": "absent(ceph_bluefs_wal_total_bytes{job=~\"$job\"}) * count(ceph_osd_metadata{job=~\"$job\"})",
     "legendFormat": "filestore"
    }
   ]
  },
  {
   "title": "OSD Size Summary",
   "type": "grafana-piechart-panel",
   "description": "The pie chart shows the various OSD sizes used within the cluster",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 8 },
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ceph_osd_stat_bytes{job=~\"$job\"} < 1099511627776)",
     "legendFormat": "<1TB"
    },
    {
     "expr": "count(ceph_osd_stat_bytes{job=~\"$job\"} >= 1099511627776 < 2199023255552)",
     "legendFormat": "<2TB"
    },
    {
     "expr": "count(ceph_osd_stat_bytes{job=~\"$job\"} >= 2199023255552 < 3298534883328)",
     "legendFormat": "<3TB"
    },
    {
     "expr": "count(ceph_osd_stat_bytes{job=~\"$job\"} >= 3298534883328 < 4398046511104)",
     "legendFormat": "<4TB"
    },
    {
     "expr": "count(ceph_osd_stat_bytes{job=~\"$job\"} >= 4398046511104 < 6597069766656)",
     "legendFormat": "<6TB"
    },
    {
     "expr": "count(ceph_osd_stat_bytes{job=~\"$job\"} >= 6597069766656 < 8796093022208)",
     "legendFormat": "<8TB"
    },
    {
     "expr": "count(ceph_osd_stat_bytes{job=~\"$job\"} >= 8796093022208 < 10995116277760)",
     "legendFormat": "<10TB"
    },
    {
     "expr": "count(ceph_osd_stat_bytes{job=~\"$job\"} >= 10995116277760 < 13194139533312)",
     "legendFormat": "<12TB"
    },
    {
     "expr": "count(ceph_osd_stat_bytes{job=~\"$job\"} >= 13194139533312)",
     "legendFormat": "<12TB+"
    }
   ]
  },
  {
   "title": "Distribution of PGs per OSD",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "# of OSDs" }
   ],
   "targets": [
    {
     "expr": "ceph_osd_numpg{job=~\"$job\"}",
     "legendFormat": "PGs per OSD"
    }
   ]
  },
  {
   "title": "OSD onode Hits Ratio",
   "type": "singlestat",
   "description": "This gauge panel shows onode Hits ratio to help determine if increasing RAM per OSD could help improve the performance of the cluster",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 8 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ceph_bluestore_onode_hits{job=~\"$job\"}) / (\n  sum(ceph_bluestore_onode_hits{job=~\"$job\"}) +\n  sum(ceph_bluestore_onode_misses{job=~\"$job\"})\n)\n"
    }
   ]
  },
  { "title": "R/W Profile", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Read/Write Profile",
   "type": "graph",
   "description": "Show the read/write workload profile overtime",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum(rate(ceph_pool_rd{job=~\"$job\"}[$__rate_interval])))",
     "legendFormat": "Reads"
    },
    {
     "expr": "round(sum(rate(ceph_pool_wr{job=~\"$job\"}[$__rate_interval])))",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Top Slow Ops",
   "type": "table",
   "description": "This table shows the 10 OSDs with the highest number of slow ops",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "topk(10,\n  (ceph_daemon_health_metrics{type=\"SLOW_OPS\", ceph_daemon=~\"osd.*\"})\n)\n"
    }
   ]
  }
 ]
}
{
 "title": "Ceph Pool Details",
 "tags": [ "ceph-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(ceph_osd_metadata, cluster)"
   },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(ceph_osd_metadata{}, job)"
   },
   {
    "name": "pool_name",
    "label": "Pool Name",
    "query": "label_values(ceph_pool_metadata{job=~\"$job\"}, name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Capacity used",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(ceph_pool_stored{job=~\"$job\"} / (ceph_pool_stored{job=~\"$job\"} + ceph_pool_max_avail{job=~\"$job\"})) *\n  on(pool_id) group_left(instance, name) ceph_pool_metadata{job=~\"$job\", name=~\"$pool_name\"}\n"
    }
   ]
  },
  {
   "title": "Time till full",
   "type": "singlestat",
   "description": "Time till pool is full assuming the average fill rate of the last 6 hours",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 0 },
   "format": "s",
   "targets": [
    {
     "expr": "(ceph_pool_max_avail{job=~\"$job\"} / deriv(ceph_pool_stored{job=~\"$job\"}[6h])) *\n  on(pool_id) group_left(instance, name) ceph_pool_metadata{job=~\"$job\", name=~\"$pool_name\"} > 0\n"
    }
   ]
  },
  {
   "title": "$pool_name Object Ingress/Egress",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ops", "label": "Objects out(-) / in(+) " }
   ],
   "targets": [
    {
     "expr": "deriv(ceph_pool_objects{job=~\"$job\"}[1m]) *\n  on(pool_id) group_left(instance, name) ceph_pool_metadata{job=~\"$job\", name=~\"$pool_name\"}\n",
     "legendFormat": "Objects per second"
    }
   ]
  },
  {
   "title": "$pool_name Client IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "iops", "label": "Read (-) / Write (+)" }
   ],
   "targets": [
    {
     "expr": "rate(ceph_pool_rd{job=~\"$job\"}[$__rate_interval]) *\n  on(pool_id) group_left(instance,name) ceph_pool_metadata{job=~\"$job\", name=~\"$pool_name\"}\n",
     "legendFormat": "reads"
    },
    {
     "expr": "rate(ceph_pool_wr{job=~\"$job\"}[$__rate_interval]) *\n  on(pool_id) group_left(instance, name) ceph_pool_metadata{job=~\"$job\", name=~\"$pool_name\"}\n",
     "legendFormat": "writes"
    }
   ]
  },
  {
   "title": "$pool_name Client Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "Bps", "label": "Read (-) / Write (+)" }
   ],
   "targets": [
    {
     "expr": "rate(ceph_pool_rd_bytes{job=~\"$job\"}[$__rate_interval]) +\n  on(pool_id) group_left(instance, name) ceph_pool_metadata{job=~\"$job\", name=~\"$pool_name\"}\n",
     "legendFormat": "reads"
    },
    {
     "expr": "rate(ceph_pool_wr_bytes{job=~\"$job\"}[$__rate_interval]) +\n  on(pool_id) group_left(instance,name) ceph_pool_metadata{job=~\"$job\", name=~\"$pool_name\"}\n",
     "legendFormat": "writes"
    }
   ]
  },
  {
   "title": "$pool_name Objects",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Objects" }
   ],
   "targets": [
    {
     "expr": "ceph_pool_objects{job=~\"$job\"} *\n  on(pool_id) group_left(instance,name) ceph_pool_metadata{job=~\"$job\", name=~\"$pool_name\"}\n",
     "legendFormat": "Number of Objects"
    }
   ]
  }
 ]
}
{
 "title": "Ceph Pools Overview",
 "tags": [ "ceph-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(ceph_osd_metadata, cluster)"
   },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(ceph_osd_metadata{}, job)"
   },
   { "name": "topk", "label": "TopK", "query": "15" }
  ]
 },
 "panels": [
  {
   "title": "Pools",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(ceph_pool_metadata{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Pools with Compression",
   "type": "singlestat",
   "description": "Count of the pools that have compression enabled",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ceph_pool_metadata{job=~\"$job\", compression_mode!=\"none\"})"
    }
   ]
  },
  {
   "title": "Total Raw Capacity",
   "type": "singlestat",
   "description": "Total raw capacity available to the cluster",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ceph_osd_stat_bytes{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Raw Capacity Consumed",
   "type": "singlestat",
   "description": "Total raw capacity consumed by user data and associated overheads (metadata + redundancy)",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ceph_pool_bytes_used{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Logical Stored ",
   "type": "singlestat",
   "description": "Total of client data stored in the cluster",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ceph_pool_stored{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Compression Savings",
   "type": "singlestat",
   "description": "A compression saving is determined as the data eligible to be compressed minus the capacity used to store the data after compression",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n  ceph_pool_compress_under_bytes{job=~\"$job\"} -\n    ceph_pool_compress_bytes_used{job=~\"$job\"}\n)\n"
    }
   ]
  },
  {
   "title": "Compression Eligibility",
   "type": "singlestat",
   "description": "Indicates how suitable the data is within the pools that are/have been enabled for compression - averaged across all pools holding compressed data",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(\n  sum(ceph_pool_compress_under_bytes{job=~\"$job\"} > 0) /\n    sum(ceph_pool_stored_raw{job=~\"$job\"} and ceph_pool_compress_under_bytes{job=~\"$job\"} > 0)\n) * 100\n"
    }
   ]
  },
  {
   "title": "Compression Factor",
   "type": "singlestat",
   "description": "This factor describes the average ratio of data eligible to be compressed divided by the data actually stored. It does not account for data written that was ineligible for compression (too small, or compression yield too low)",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n  ceph_pool_compress_under_bytes{job=~\"$job\"} > 0)\n    / sum(ceph_pool_compress_bytes_used{job=~\"$job\"} > 0\n)\n"
    }
   ]
  },
  {
   "title": "Pool Overview",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "(\n  ceph_pool_compress_under_bytes{job=~\"$job\"} /\n    ceph_pool_compress_bytes_used{job=~\"$job\"} > 0\n) and on(pool_id) (\n  (\n    (ceph_pool_compress_under_bytes{job=~\"$job\"} > 0) /\n      ceph_pool_stored_raw{job=~\"$job\"}\n  ) * 100 > 0.5\n)\n",
     "legendFormat": "A"
    },
    {
     "expr": "ceph_pool_max_avail{job=~\"$job\"} *\n  on(pool_id) group_left(name) ceph_pool_metadata{job=~\"$job\"}\n",
     "legendFormat": "B"
    },
    {
     "expr": "(\n  (ceph_pool_compress_under_bytes{job=~\"$job\"} > 0) /\n    ceph_pool_stored_raw{job=~\"$job\"}\n) * 100\n",
     "legendFormat": "C"
    },
    {
     "expr": "ceph_pool_percent_used{job=~\"$job\"} *\n  on(pool_id) group_left(name) ceph_pool_metadata{job=~\"$job\"}\n",
     "legendFormat": "D"
    },
    {
     "expr": "ceph_pool_compress_under_bytes{job=~\"$job\"} -\n  ceph_pool_compress_bytes_used{job=~\"$job\"} > 0\n",
     "legendFormat": "E"
    },
    {
     "expr": "delta(ceph_pool_stored{job=~\"$job\"}[5d])",
     "legendFormat": "F"
    },
    {
     "expr": "rate(ceph_pool_rd{job=~\"$job\"}[$__rate_interval])\n  + rate(ceph_pool_wr{job=~\"$job\"}[$__rate_interval])\n",
     "legendFormat": "G"
    },
    {
     "expr": "rate(ceph_pool_rd_bytes{job=~\"$job\"}[$__rate_interval]) +\n  rate(ceph_pool_wr_bytes{job=~\"$job\"}[$__rate_interval])\n",
     "legendFormat": "H"
    },
    {
     "expr": "ceph_pool_metadata{job=~\"$job\"}",
     "legendFormat": "I"
    },
    {
     "expr": "ceph_pool_stored{job=~\"$job\"} * on(pool_id) group_left ceph_pool_metadata{job=~\"$job\"}",
     "legendFormat": "J"
    },
    {
     "expr": "ceph_pool_metadata{job=~\"$job\", compression_mode!=\"none\"}",
     "legendFormat": "K"
    },
    { "legendFormat": "L" }
   ]
  },
  {
   "title": "Top $topk Client IOPS by Pool",
   "type": "graph",
   "description": "This chart shows the sum of read and write IOPS from all clients by pool",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "IOPS" }
   ],
   "targets": [
    {
     "expr": "topk($topk,\n  round(\n    (\n      rate(ceph_pool_rd{job=~\"$job\"}[$__rate_interval]) +\n        rate(ceph_pool_wr{job=~\"$job\"}[$__rate_interval])\n    ), 1\n  ) * on(pool_id) group_left(instance,name) ceph_pool_metadata{job=~\"$job\"})\n",
     "legendFormat": "{{name}} "
    },
    {
     "expr": "topk($topk,\n  rate(ceph_pool_wr{job=~\"$job\"}[$__rate_interval]) +\n    on(pool_id) group_left(instance,name) ceph_pool_metadata{job=~\"$job\"}\n)\n",
     "legendFormat": "{{name}} - write"
    }
   ]
  },
  {
   "title": "Top $topk Client Bandwidth by Pool",
   "type": "graph",
   "description": "The chart shows the sum of read and write bytes from all clients, by pool",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "Bps", "label": "Throughput" }
   ],
   "targets": [
    {
     "expr": "topk($topk,\n  (\n    rate(ceph_pool_rd_bytes{job=~\"$job\"}[$__rate_interval]) +\n      rate(ceph_pool_wr_bytes{job=~\"$job\"}[$__rate_interval])\n  ) * on(pool_id) group_left(instance, name) ceph_pool_metadata{job=~\"$job\"}\n)\n",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pool Capacity Usage (RAW)",
   "type": "graph",
   "description": "Historical view of capacity usage, to help identify growth and trends in pool consumption",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes", "label": "Capacity Used" }
   ],
   "targets": [
    {
     "expr": "ceph_pool_bytes_used{job=~\"$job\"} * on(pool_id) group_right ceph_pool_metadata{job=~\"$job\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}
{
 "title": "RGW Instance Detail",
 "tags": [
  "ceph-mixin",
  "overview"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(ceph_osd_metadata, cluster)"
   },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(ceph_osd_metadata{}, job)"
   },
   {
    "name": "rgw_servers",
    "query": "label_values(ceph_rgw_metadata{job=~\"$job\"}, ceph_daemon)"
   }
  ]
 },
 "panels": [
  { "title": "RGW Host Detail : $rgw_servers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$rgw_servers GET/PUT Latencies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (instance_id) (\n  rate(ceph_rgw_get_initial_lat_sum{job=~\"$job\"}[$__rate_interval]) /\n    rate(ceph_rgw_get_initial_lat_count{job=~\"$job\"}[$__rate_interval])\n) * on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{job=~\"$job\", ceph_daemon=~\"$rgw_servers\"}\n",
     "legendFormat": "GET {{ceph_daemon}}"
    },
    {
     "expr": "sum by (instance_id) (\n  rate(ceph_rgw_put_initial_lat_sum{job=~\"$job\"}[$__rate_interval]) /\n    rate(ceph_rgw_put_initial_lat_count{job=~\"$job\"}[$__rate_interval])\n) * on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{job=~\"$job\", ceph_daemon=~\"$rgw_servers\"}\n",
     "legendFormat": "PUT {{ceph_daemon}}"
    }
   ]
  },
  {
   "title": "Bandwidth by HTTP Operation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(ceph_rgw_get_b{job=~\"$job\"}[$__rate_interval]) *\n  on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{job=~\"$job\", ceph_daemon=~\"$rgw_servers\"}\n",
     "legendFormat": "GETs {{ceph_daemon}}"
    },
    {
     "expr": "rate(ceph_rgw_put_b{job=~\"$job\"}[$__rate_interval]) *\n  on (instance_id) group_left (ceph_daemon)\n  ceph_rgw_metadata{job=~\"$job\", ceph_daemon=~\"$rgw_servers\"}\n",
     "legendFormat": "PUTs {{ceph_daemon}}"
    }
   ]
  },
  {
   "title": "HTTP Request Breakdown",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 13, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ceph_rgw_failed_req{job=~\"$job\"}[$__rate_interval]) *\n  on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{job=~\"$job\",ceph_daemon=~\"$rgw_servers\"}\n",
     "legendFormat": "Requests Failed {{ceph_daemon}}"
    },
    {
     "expr": "rate(ceph_rgw_get{job=~\"$job\"}[$__rate_interval]) *\n  on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{job=~\"$job\", ceph_daemon=~\"$rgw_servers\"}\n",
     "legendFormat": "GETs {{ceph_daemon}}"
    },
    {
     "expr": "rate(ceph_rgw_put{job=~\"$job\"}[$__rate_interval]) *\n  on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{job=~\"$job\", ceph_daemon=~\"$rgw_servers\"}\n",
     "legendFormat": "PUTs {{ceph_daemon}}"
    },
    {
     "expr": "(\n  rate(ceph_rgw_req{job=~\"$job\"}[$__rate_interval]) -\n    (\n      rate(ceph_rgw_get{job=~\"$job\"}[$__rate_interval]) +\n        rate(ceph_rgw_put{job=~\"$job\"}[$__rate_interval])\n    )\n) * on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{job=~\"$job\", ceph_daemon=~\"$rgw_servers\"}\n",
     "legendFormat": "Other {{ceph_daemon}}"
    }
   ]
  },
  {
   "title": "Workload Breakdown",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(ceph_rgw_failed_req{job=~\"$job\"}[$__rate_interval]) *\n  on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{job=~\"$job\", ceph_daemon=~\"$rgw_servers\"}\n",
     "legendFormat": "Failures {{ceph_daemon}}"
    },
    {
     "expr": "rate(ceph_rgw_get{job=~\"$job\"}[$__rate_interval]) *\n  on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{job=~\"$job\", ceph_daemon=~\"$rgw_servers\"}\n",
     "legendFormat": "GETs {{ceph_daemon}}"
    },
    {
     "expr": "rate(ceph_rgw_put{job=~\"$job\"}[$__rate_interval]) *\n  on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{job=~\"$job\", ceph_daemon=~\"$rgw_servers\"}\n",
     "legendFormat": "PUTs {{ceph_daemon}}"
    },
    {
     "expr": "(\n  rate(ceph_rgw_req{job=~\"$job\"}[$__rate_interval]) -\n    (\n      rate(ceph_rgw_get{job=~\"$job\"}[$__rate_interval]) +\n        rate(ceph_rgw_put{job=~\"$job\"}[$__rate_interval])\n    )\n) * on (instance_id) group_left (ceph_daemon)\n  ceph_rgw_metadata{job=~\"$job\", ceph_daemon=~\"$rgw_servers\"}\n",
     "legendFormat": "Other (DELETE,LIST) {{ceph_daemon}}"
    }
   ]
  }
 ]
}
{
 "title": "RGW Overview",
 "tags": [
  "ceph-mixin",
  "overview"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(ceph_osd_metadata, cluster)"
   },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(ceph_osd_metadata{}, job)"
   },
   {
    "name": "rgw_servers",
    "query": "label_values(ceph_rgw_metadata{job=~\"$job\"}, ceph_daemon)"
   },
   {
    "name": "code",
    "label": "HTTP Code",
    "query": "label_values(haproxy_server_http_responses_total{job=~\"$job_haproxy\", instance=~\"$ingress_service\"}, code)"
   },
   {
    "name": "job_haproxy",
    "label": "job haproxy",
    "query": "label_values(haproxy_server_status, job)"
   },
   {
    "name": "ingress_service",
    "label": "Ingress Service",
    "query": "label_values(haproxy_server_status{job=~\"$job_haproxy\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "RGW Overview - All Gateways", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average GET/PUT Latencies by RGW Instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "label_replace(\n  rate(ceph_rgw_get_initial_lat_sum{job=~\"$job\"}[$__rate_interval]) /\n    rate(ceph_rgw_get_initial_lat_count{job=~\"$job\"}[$__rate_interval]) *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{job=~\"$job\"},\n  \"rgw_host\", \"$1\", \"ceph_daemon\", \"rgw.(.*)\"\n)\n",
     "legendFormat": "GET {{rgw_host}}"
    },
    {
     "expr": "label_replace(\n  rate(ceph_rgw_put_initial_lat_sum{job=~\"$job\"}[$__rate_interval]) /\n    rate(ceph_rgw_put_initial_lat_count{job=~\"$job\"}[$__rate_interval]) *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{job=~\"$job\"},\n  \"rgw_host\", \"$1\", \"ceph_daemon\", \"rgw.(.*)\"\n)\n",
     "legendFormat": "PUT {{rgw_host}}"
    }
   ]
  },
  {
   "title": "Total Requests/sec by RGW Instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (rgw_host) (\n  label_replace(\n    rate(ceph_rgw_req{job=~\"$job\"}[$__rate_interval]) *\n      on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{job=~\"$job\"},\n    \"rgw_host\", \"$1\", \"ceph_daemon\", \"rgw.(.*)\"\n  )\n)\n",
     "legendFormat": "{{rgw_host}}"
    }
   ]
  },
  {
   "title": "GET Latencies by RGW Instance",
   "type": "graph",
   "description": "Latencies are shown stacked, without a yaxis to provide a visual indication of GET latency imbalance across RGW hosts",
   "gridPos": { "h": 7, "w": 6, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "label_replace(\n  rate(ceph_rgw_get_initial_lat_sum{job=~\"$job\"}[$__rate_interval]) /\n    rate(ceph_rgw_get_initial_lat_count{job=~\"$job\"}[$__rate_interval]) *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{job=~\"$job\"},\n  \"rgw_host\", \"$1\", \"ceph_daemon\", \"rgw.(.*)\"\n)\n",
     "legendFormat": "{{rgw_host}}"
    }
   ]
  },
  {
   "title": "Bandwidth Consumed by Type",
   "type": "graph",
   "description": "Total bytes transferred in/out of all radosgw instances within the cluster",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ceph_rgw_get_b{job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "GETs"
    },
    {
     "expr": "sum(rate(ceph_rgw_put_b{job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "PUTs"
    }
   ]
  },
  {
   "title": "Bandwidth by RGW Instance",
   "type": "graph",
   "description": "Total bytes transferred in/out through get/put operations, by radosgw instance",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum by (instance_id) (\n  rate(ceph_rgw_get_b{job=~\"$job\"}[$__rate_interval]) +\n    rate(ceph_rgw_put_b{job=~\"$job\"}[$__rate_interval])) *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{job=~\"$job\"},\n  \"rgw_host\", \"$1\", \"ceph_daemon\", \"rgw.(.*)\"\n)\n",
     "legendFormat": "{{rgw_host}}"
    }
   ]
  },
  {
   "title": "PUT Latencies by RGW Instance",
   "type": "graph",
   "description": "Latencies are shown stacked, without a yaxis to provide a visual indication of PUT latency imbalance across RGW hosts",
   "gridPos": { "h": 6, "w": 6, "x": 15, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "label_replace(\n  rate(ceph_rgw_put_initial_lat_sum{job=~\"$job\"}[$__rate_interval]) /\n    rate(ceph_rgw_put_initial_lat_count{job=~\"$job\"}[$__rate_interval]) *\n    on (instance_id) group_left (ceph_daemon) ceph_rgw_metadata{job=~\"$job\"},\n  \"rgw_host\", \"$1\", \"ceph_daemon\", \"rgw.(.*)\"\n)\n",
     "legendFormat": "{{rgw_host}}"
    }
   ]
  },
  { "title": "RGW Overview - HAProxy Metrics", "type": "row", "gridPos": { "h": 12, "w": 9, "x": 0, "y": 12 } },
  {
   "title": "Total responses by HTTP code",
   "type": "graph",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(\n    haproxy_frontend_http_responses_total{code=~\"$code\", job=~\"$job_haproxy\", instance=~\"$ingress_service\", proxy=~\"frontend\"}[$__rate_interval]\n  )\n) by (code)\n",
     "legendFormat": "Frontend {{ code }}"
    },
    {
     "expr": "sum(\n  rate(\n    haproxy_backend_http_responses_total{code=~\"$code\", job=~\"$job_haproxy\", instance=~\"$ingress_service\", proxy=~\"backend\"}[$__rate_interval]\n  )\n) by (code)\n",
     "legendFormat": "Backend {{ code }}"
    }
   ]
  },
  {
   "title": "Total requests / responses",
   "type": "graph",
   "gridPos": { "h": 12, "w": 5, "x": 5, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(\n    haproxy_frontend_http_requests_total{proxy=~\"frontend\", job=~\"$job_haproxy\", instance=~\"$ingress_service\"}[$__rate_interval]\n  )\n) by (instance)\n",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(\n  rate(\n    haproxy_backend_response_errors_total{proxy=~\"backend\", job=~\"$job_haproxy\", instance=~\"$ingress_service\"}[$__rate_interval]\n  )\n) by (instance)\n",
     "legendFormat": "Response errors"
    },
    {
     "expr": "sum(\n  rate(\n    haproxy_frontend_request_errors_total{proxy=~\"frontend\", job=~\"$job_haproxy\", instance=~\"$ingress_service\"}[$__rate_interval]\n  )\n) by (instance)\n",
     "legendFormat": "Requests errors"
    },
    {
     "expr": "sum(\n  rate(\n    haproxy_backend_redispatch_warnings_total{proxy=~\"backend\", job=~\"$job_haproxy\", instance=~\"$ingress_service\"}[$__rate_interval]\n  )\n) by (instance)\n",
     "legendFormat": "Backend redispatch"
    },
    {
     "expr": "sum(\n  rate(\n    haproxy_backend_retry_warnings_total{proxy=~\"backend\", job=~\"$job_haproxy\", instance=~\"$ingress_service\"}[$__rate_interval]\n  )\n) by (instance)\n",
     "legendFormat": "Backend retry"
    },
    {
     "expr": "sum(\n  rate(\n    haproxy_frontend_requests_denied_total{proxy=~\"frontend\", job=~\"$job_haproxy\", instance=~\"$ingress_service\"}[$__rate_interval]\n  )\n) by (instance)\n",
     "legendFormat": "Request denied"
    },
    {
     "expr": "sum(\n  haproxy_backend_current_queue{proxy=~\"backend\", job=~\"$job_haproxy\", instance=~\"$ingress_service\"}\n) by (instance)\n",
     "legendFormat": "Backend Queued"
    }
   ]
  },
  {
   "title": "Total number of connections",
   "type": "graph",
   "gridPos": { "h": 12, "w": 5, "x": 10, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(\n    haproxy_frontend_connections_total{proxy=~\"frontend\", job=~\"$job_haproxy\", instance=~\"$ingress_service\"}[$__rate_interval]\n  )\n) by (instance)\n",
     "legendFormat": "Front"
    },
    {
     "expr": "sum(\n  rate(\n    haproxy_backend_connection_attempts_total{proxy=~\"backend\", job=~\"$job_haproxy\", instance=~\"$ingress_service\"}[$__rate_interval]\n  )\n) by (instance)\n",
     "legendFormat": "Back"
    },
    {
     "expr": "sum(\n  rate(\n    haproxy_backend_connection_errors_total{proxy=~\"backend\", job=~\"$job_haproxy\", instance=~\"$ingress_service\"}[$__rate_interval]\n  )\n) by (instance)\n",
     "legendFormat": "Back errors"
    }
   ]
  },
  {
   "title": "Current total of incoming / outgoing bytes",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 15, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(\n    haproxy_frontend_bytes_in_total{proxy=~\"frontend\", job=~\"$job_haproxy\", instance=~\"$ingress_service\"}[$__rate_interval]\n  ) * 8\n) by (instance)\n",
     "legendFormat": "IN Front"
    },
    {
     "expr": "sum(\n  rate(\n    haproxy_frontend_bytes_out_total{proxy=~\"frontend\", job=~\"$job_haproxy\", instance=~\"$ingress_service\"}[$__rate_interval]\n  ) * 8\n) by (instance)\n",
     "legendFormat": "OUT Front"
    },
    {
     "expr": "sum(\n  rate(\n    haproxy_backend_bytes_in_total{proxy=~\"backend\", job=~\"$job_haproxy\", instance=~\"$ingress_service\"}[$__rate_interval]\n  ) * 8\n) by (instance)\n",
     "legendFormat": "IN Back"
    },
    {
     "expr": "sum(\n  rate(\n    haproxy_backend_bytes_out_total{proxy=~\"backend\", job=~\"$job_haproxy\", instance=~\"$ingress_service\"}[$__rate_interval]\n  ) * 8\n) by (instance)\n",
     "legendFormat": "OUT Back"
    }
   ]
  }
 ]
}
{
 "title": "RGW Sync Overview",
 "tags": [
  "ceph-mixin",
  "overview"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(ceph_osd_metadata, cluster)"
   },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(ceph_osd_metadata{}, job)"
   },
   {
    "name": "rgw_servers",
    "query": "label_values(ceph_rgw_metadata{job=~\"$job\"}, ceph_daemon)"
   }
  ]
 },
 "panels": [
  {
   "title": "Replication (throughput) from Source Zone",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (source_zone) (rate(ceph_data_sync_from_zone_fetch_bytes_sum{job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{source_zone}}"
    }
   ]
  },
  {
   "title": "Replication (objects) from Source Zone",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Objects/s" }
   ],
   "targets": [
    {
     "expr": "sum by (source_zone) (rate(ceph_data_sync_from_zone_fetch_bytes_count{job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{source_zone}}"
    }
   ]
  },
  {
   "title": "Polling Request Latency from Source Zone",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by (source_zone) (rate(ceph_data_sync_from_zone_poll_latency_sum{job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{source_zone}}"
    }
   ]
  },
  {
   "title": "Unsuccessful Object Replications from Source Zone",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "Count/s" }
   ],
   "targets": [
    {
     "expr": "sum by (source_zone) (rate(ceph_data_sync_from_zone_fetch_errors{job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{source_zone}}"
    }
   ]
  }
 ]
}
{
 "title": "RBD Details",
 "description": "Detailed Performance of RBD Images (IOPS/Throughput/Latency)",
 "tags": [ "ceph-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(ceph_osd_metadata, cluster)"
   },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(ceph_osd_metadata{}, job)"
   },
   { "name": "pool", "query": "label_values(pool)" },
   { "name": "image", "query": "label_values(image)" }
  ]
 },
 "panels": [
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(ceph_rbd_write_ops{job=~\"$job\", pool=\"$pool\", image=\"$image\"}[$__rate_interval])",
     "legendFormat": "{{pool}} Write"
    },
    {
     "expr": "rate(ceph_rbd_read_ops{job=~\"$job\", pool=\"$pool\", image=\"$image\"}[$__rate_interval])",
     "legendFormat": "{{pool}} Read"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(ceph_rbd_write_bytes{job=~\"$job\", pool=\"$pool\", image=\"$image\"}[$__rate_interval])",
     "legendFormat": "{{pool}} Write"
    },
    {
     "expr": "rate(ceph_rbd_read_bytes{job=~\"$job\", pool=\"$pool\", image=\"$image\"}[$__rate_interval])",
     "legendFormat": "{{pool}} Read"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "rate(ceph_rbd_write_latency_sum{job=~\"$job\", pool=\"$pool\", image=\"$image\"}[$__rate_interval]) /\n  rate(ceph_rbd_write_latency_count{job=~\"$job\", pool=\"$pool\", image=\"$image\"}[$__rate_interval])\n",
     "legendFormat": "{{pool}} Write"
    },
    {
     "expr": "rate(ceph_rbd_read_latency_sum{job=~\"$job\", pool=\"$pool\", image=\"$image\"}[$__rate_interval]) /\n  rate(ceph_rbd_read_latency_count{job=~\"$job\", pool=\"$pool\", image=\"$image\"}[$__rate_interval])\n",
     "legendFormat": "{{pool}} Read"
    }
   ]
  }
 ]
}
{
 "title": "RBD Overview",
 "tags": [
  "ceph-mixin",
  "overview"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(ceph_osd_metadata, cluster)"
   },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(ceph_osd_metadata{}, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum(rate(ceph_rbd_write_ops{job=~\"$job\"}[$__rate_interval])))",
     "legendFormat": "Writes"
    },
    {
     "expr": "round(sum(rate(ceph_rbd_read_ops{job=~\"$job\"}[$__rate_interval])))",
     "legendFormat": "Reads"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "round(sum(rate(ceph_rbd_write_bytes{job=~\"$job\"}[$__rate_interval])))",
     "legendFormat": "Write"
    },
    {
     "expr": "round(sum(rate(ceph_rbd_read_bytes{job=~\"$job\"}[$__rate_interval])))",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "round(\n  sum(rate(ceph_rbd_write_latency_sum{job=~\"$job\"}[$__rate_interval])) /\n    sum(rate(ceph_rbd_write_latency_count{job=~\"$job\"}[$__rate_interval]))\n)\n",
     "legendFormat": "Write"
    },
    {
     "expr": "round(\n  sum(rate(ceph_rbd_read_latency_sum{job=~\"$job\"}[$__rate_interval])) /\n    sum(rate(ceph_rbd_read_latency_count{job=~\"$job\"}[$__rate_interval]))\n)\n",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Highest IOPS",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "topk(10,\n  (\n    sort((\n      rate(ceph_rbd_write_ops{job=~\"$job\"}[$__rate_interval]) +\n        on (image, pool, namespace) rate(ceph_rbd_read_ops{job=~\"$job\"}[$__rate_interval])\n    ))\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Highest Throughput",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "topk(10,\n  sort(\n    sum(\n      rate(ceph_rbd_read_bytes{job=~\"$job\"}[$__rate_interval]) +\n        rate(ceph_rbd_write_bytes{job=~\"$job\"}[$__rate_interval])\n    ) by (pool, image, namespace)\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Highest Latency",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "topk(10,\n  sum(\n    rate(ceph_rbd_write_latency_sum{job=~\"$job\"}[$__rate_interval]) /\n      clamp_min(rate(ceph_rbd_write_latency_count{job=~\"$job\"}[$__rate_interval]), 1) +\n      rate(ceph_rbd_read_latency_sum{job=~\"$job\"}[$__rate_interval]) /\n      clamp_min(rate(ceph_rbd_read_latency_count{job=~\"$job\"}[$__rate_interval]), 1)\n  ) by (pool, image, namespace)\n)\n"
    }
   ]
  }
 ]
}