apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: monitoring
  name: grafana-pvc
spec:
  storageClassName: rook-cephfs
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
