apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: k8s-experience
  source:
    repoURL: https://github.com/mnlipp/kubernetes-experience.git
    path: 005_k3s/metallb
  destination:
    name: in-cluster
    namespace: metallb-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
