apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook
  namespace: argocd
spec:
  project: k8s-experience
  source:
    repoURL: https://github.com/mnlipp/kubernetes-experience.git
    path: 015_rook
  destination:
    name: in-cluster
    namespace: rook-ceph
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
