apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/rook/rook/raw/release-1.13/deploy/examples/crds.yaml
- https://github.com/rook/rook/raw/release-1.13/deploy/examples/common.yaml
- https://github.com/rook/rook/raw/release-1.13/deploy/examples/operator.yaml
- https://github.com/rook/rook/raw/release-1.13/deploy/examples/cluster.yaml
- https://github.com/rook/rook/raw/release-1.13/deploy/examples/monitoring/rbac.yaml
- 060_dashboard-ingress.yaml
- 070_filesystem-mainshare.yaml
- 080_client-mainshare.yaml
- 090_filesystem-podstorage.yaml
- 100_storageclass-podstorage.yaml
- 110_client-podstorage.yaml

patches:
- patch: |-
    kind: ConfigMap
    apiVersion: v1
    metadata:
      namespace: rook-ceph
      name: rook-ceph-operator-config
    data:
      CSI_PLUGIN_ENABLE_SELINUX_HOST_MOUNT: "true"
      ROOK_ENABLE_DISCOVERY_DAEMON: "true"
  
- patch: |-
    apiVersion: ceph.rook.io/v1
    kind: CephCluster
    metadata:
      name: rook-ceph
      namespace: rook-ceph # namespace:cluster
    spec:
      mgr:
        modules:
        - name: rook
          enabled: true
      dashboard:
        enabled: true
        port: 8080
        ssl: false
      monitoring:
        enabled: true
      network:
        # Because we want to support client access
        provider: host
      resources:
        osd:
          requests:
            cpu: "1000m"
            memory: "1024Mi"
