apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: k8s-experience
  source:
    repoURL: ssh://gitolite3@hestia.lan.mnl.de/k8s-experience-tc1.git
    path: 999_misc/k3s-configuration/metallb
  destination:
    name: in-cluster
    namespace: metallb-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
