apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: k8s-experience-olymp
  source:
    repoURL: https://charts.jetstack.io
    targetRevision: v1.12.2
    chart: cert-manager
    helm:
      parameters:
        - name: installCRDs
          value: "true"
  destination:
    name: in-cluster
    namespace: cert-manager
  syncPolicy:
    syncOptions:
      - CreateNamespace=true